apiVersion: apps/v1
kind: Deployment
metadata:
    name: svc-products-deployment
spec:
    selector:
        matchLabels:
            app: svc-products
    template:
        metadata:
            labels:
                app: svc-products
        spec:
            containers:
                - name: svc-products
                  image: svc-products
                  imagePullPolicy: Never
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3000
