apiVersion: v1
kind: Service
metadata:
    name: svc-products-service
spec:
    type: NodePort
    selector:
        app: svc-products
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
          name: svc-products-service
